export default [
  {
    id: 1,
    logo:'link.com',
    postedOn: "2023-10-28",
    title: "Software Engineer (Frontend)",
    company: "Technovation Inc.",
    type: "Full-time",
    experience: "2-4 years",
    location: "remote",
    skills: ["JavaScript", "React", "HTML", "CSS"],
    jobLink: "https://www.example.com/jobs/software-engineer-frontend-1",
  },
  {
    id: 2,
    postedOn: "2024-06-07",
    title: "Data Analyst",
    company: "Acme Analytics",
    type: "Contract",
    experience: "Entry-level",
    location: "hybrid",
    skills: ["Python", "SQL", "Data Visualization", "Tableau"],
    jobLink: "https://www.example.com/jobs/data-analyst-2",
  },
  {
    id: 3,
    postedOn: "2024-05-15",
    title: "UX/UI Designer",
    company: "Creative Studios",
    type: "Part-time",
    experience: "3+ years",
    location: "on site",
    skills: ["Figma", "Adobe XD", "User Research", "UI/UX Principles"],
    jobLink: "https://www.example.com/jobs/ux-ui-designer-3",
  },
  {
    id: 4,
    postedOn: "2024-04-20",
    title: "Marketing Manager",
    company: "Global Solutions",
    type: "Full-time",
    experience: "5+ years",
    location: "remote",
    skills: [
      "Social Media Marketing",
      "SEO",
      "Content Marketing",
      "Campaign Management",
    ],
    jobLink: "https://www.example.com/jobs/marketing-manager-4",
  },
  {
    id: 5,
    postedOn: "2024-03-08",
    title: "Software Developer (Backend)",
    company: "InnoTech",
    type: "Full-time",
    experience: "Mid-level (4-6 years)",
    location: "hybrid",
    skills: ["Java", "Spring Boot", "Microservices", "Cloud Computing"],
    jobLink: "https://www.example.com/jobs/software-developer-backend-5",
  },
  {
    id: 6,
    postedOn: "2023-10-28",
    title: "ios Developer",
    company: "Apple",
    type: "Full-Time",
    experience: "Mid-level",
    location: "Remote",
    skills: ["swiftUi", "uiKit", "Core Data"],
    jobLink: "https://www.apple.com/careers/in/",
  },
];
